# Generated by Django 5.2.5 on 2025-08-07 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("upload_STEP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="occ_docs/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occ_documents",
                        to="upload_STEP.stepfile",
                    ),
                ),
            ],
        ),
    ]
