# Generated by Django 4.2.21 on 2025-08-11 11:32

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the shape', max_length=200)),
                ('source_step', models.FileField(help_text='Original STEP file upload', upload_to='shapes/step/')),
                ('canonical_brep', models.FileField(blank=True, help_text='Planarized, XOY-aligned face in BREP format', null=True, upload_to='shapes/brep/')),
                ('preview_svg', models.FileField(blank=True, help_text='Quick thumbnail preview', null=True, upload_to='shapes/preview/')),
                ('bbox_w_mm', models.FloatField(blank=True, help_text='Bounding box width in millimeters', null=True)),
                ('bbox_h_mm', models.FloatField(blank=True, help_text='Bounding box height in millimeters', null=True)),
                ('area_mm2', models.FloatField(blank=True, help_text='Area in square millimeters', null=True)),
                ('has_holes', models.BooleanField(default=False, help_text='Whether the shape contains holes')),
                ('default_edge', models.CharField(choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Left', 'Left'), ('Right', 'Right')], default='Left', help_text='Default edge for placement', max_length=10)),
                ('default_offset_mm', models.FloatField(default=0.0, help_text='Default offset from edge in millimeters')),
                ('attach_x_mm', models.FloatField(default=0.0, help_text="X coordinate of attach point in shape's local frame")),
                ('attach_y_mm', models.FloatField(default=0.0, help_text="Y coordinate of attach point in shape's local frame")),
                ('attach_angle_deg', models.FloatField(default=0.0, help_text='Rotation angle in degrees for the attach frame', validators=[django.core.validators.MinValueValidator(-360), django.core.validators.MaxValueValidator(360)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shape Asset',
                'verbose_name_plural': 'Shape Assets',
                'ordering': ['name'],
            },
        ),
    ]
