# Generated by Django 5.2.5 on 2025-08-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapeasset',
            name='source_brep',
            field=models.FileField(blank=True, help_text='Original BREP file upload', null=True, upload_to='shapes/brep/'),
        ),
        migrations.AlterField(
            model_name='shapeasset',
            name='source_step',
            field=models.FileField(blank=True, help_text='Original STEP file upload (legacy)', null=True, upload_to='shapes/step/'),
        ),
    ]
