# Generated by Django 5.2.5 on 2025-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0002_shapeasset_source_brep_alter_shapeasset_source_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapeasset',
            name='shape_type',
            field=models.CharField(choices=[('internal_cutout', 'Internal Cutout'), ('edge_affecting', 'Edge Affecting')], default='internal_cutout', help_text='Type of shape for Panel2D library integration', max_length=20),
        ),
    ]
